### ISSUE TITLE
Error: Error creating package

### ISSUE THREAD

**Issue by simon387** [unindented/electron-installer-windows#169] opened 2017-03-10 21:05 UTC
**What version of `electron-installer-windows` are you using?**
 "version": "0.2.0"

**What version of `node` and `npm` are you using?**
node v6.9.5
npm 3.10.10

**What operating system are you using?**
windows10 64

**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
no

**If not, paste here the output of the following commands:**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose stack Error: missing script: build
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:329:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
5 verbose cwd C:\electron\electron-installer-windows-master
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
8 error node v6.9.5
9 error npm  v3.10.10
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

```
$ git clone https://github.com/unindented/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
PS C:\electron\daocstarter> electron-installer-windows --src dist/app-win32-x64/ --dest dist/installers/

on repo 
https://github.com/simon387/daocstarter

**What did you expect to happen?**
build

**What actually happened?**

    at C:\Users\Simone\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:273:21
    at ChildProcess.<anonymous> (C:\Users\Simone\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:62:5)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 'Error: Error creating package: Error executing file (1): \nC:\\Users\\Simone\\AppData\\Roaming\\npm\\node_modules\\electron-insta
ller-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\Simone\\AppData\\Local\\Temp\\electron-117210-2396-jau0gf.r88785xw29\\daocstarter_1.0.0\\nuget\\daocstarter.nuspec -BasePath C:\\Users\\Simone\\AppData\
\Local\\Temp\\electron-117210-2396-jau0gf.r88785xw29\\daocstarter_1.0.0\\daocstarter -OutputDirectory C:\\Users\\Simone\\AppData\\Local\\Temp\\electron-117210-2396-jau0gf.r88785xw29\\daocstarter_1.0.0\\nuget
 -NoDefaultExcludes\nURI non valido: impossibile determinare il formato dell\'URI.\r\n\n    at C:\\Users\\Simone\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:273:21\n
  at ChildProcess.<anonymous> (C:\\Users\\Simone\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (events.js:111:20)\n    at ChildProcess.emit (events
.js:191:7)\n    at maybeClose (internal/child_process.js:877:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)'

**Comment by unindented** [comment] 2017-03-11 03:05
Duplicate of https://github.com/unindented/electron-installer-windows/issues/151

**Closed by unindented** 2017-03-11 03:05 UTC
