### ISSUE TITLE
no shortcuts created anywhere

### ISSUE THREAD

**Issue by CraigZych** [unindented/electron-installer-windows#217] opened 2017-08-21 14:54 UTC
**What version of `electron-installer-windows` are you using?**
0.2.0

**What version of `node` and `npm` are you using?**
node 7.7.4
npm 4.1.2
**What operating system are you using?**
windows 7
**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
yes

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**

**What did you expect to happen?**
Start menu or desktop shortcut
**What actually happened?**
Opens program but doesn't provide option to reopen anywhere

Should there not be a start menu program created and possibly the option to create a desktop icon?

**Comment by freeneutron** [comment] 2018-01-28 20:40
i have a like problem

**Comment by fcastilloec** [comment] 2018-04-09 20:03
Can you guys check if this is still valid for the latest release? I've tried with a couple of apps and they all have shortcuts created.
I'll wait a couple of days to see what you guys say, otherwise, I'll close this issue. And if the problem continues, we can reopen it.

**Closed** 2018-05-12 21:15 UTC

**Comment by monsterdream** [comment] 2018-07-28 20:44
I can confirm that I have that same problem, I just downloaded everything fresh, newest versions of everything. I'm getting installer, installing nice but any icons at all. If I will try to install my app second time, first it will open it (so it's there somewhere), it will close this windows and show another one with working app.

**Comment by fcastilloec** [comment] 2018-10-02 18:39
@monsterdream can you share your config file? The majority of the time, this is not an error but rather it's just a misconfiguration, or even more common, a failure to add a proper path to `icon` when creating a `BrowserWindow` in electron.

**Comment by dachinat** [comment] 2018-11-26 22:47
@fcastilloec Can you help? Shortcuts are not generated for me. Also app is installed in LocalData...

```
const installer = require('electron-installer-windows');
const path = require('path');

const options = {
    src: path.resolve(__dirname, 'dist', 'barcode-app-win32-ia32'),
    dest: path.resolve(__dirname, 'installer'),
    icon: path.resolve(__dirname, 'assets', 'icon.ico'),
    iconUrl: path.resolve(__dirname, 'assets', 'icon.ico'),
    tags: [
        "Utility"
    ],
};

console.log('Creating package (this may take a while)');

installer(options)......
```

**Comment by fcastilloec** [comment] 2018-11-27 00:35
@dachinat The only error I see in your code is `iconUrl` which has to be a URL and not a path. This icon is the one used for shortcuts, and because Windows can download it from the URL, it might not be creating the shortcut. Our README mentions that this has to be a URL.
If that doesn't solve it, please run your script with `DEBUG=electron-installer-windows *your script*` from bash (even for Windows, powershell and cmd don't work the same), copy/paste the output to a gist and let me know the link here. Or even better just DM me on twitter `(at)fcastillo` because Github issues shouldn't be for asking question

**Comment by dachinat** [comment] 2018-11-27 00:36
@fcastilloec Hey, thanks a lot! I'll follow your suggestions

**Comment by fcastilloec** [comment] 2018-11-27 03:36
For anybody that's having problems with shortcuts. This module uses [`Squirrel`](https://github.com/Squirrel/Squirrel.Windows) at its core. It seems that people might not be handling Squirrel events that rise when installing the app. Your application is expected to handle all this events when installing, updating or uninstalling your app. If this is not done, then your app won't exit properly (or at all) when installing it, which leads to not creating any shortcuts.

I suggest people use [`electron-squirrel-startup`](https://github.com/mongodb-js/electron-squirrel-startup#electron-squirrel-startup---) module, which automatically will handle all Squirrel events.
