### ISSUE TITLE
Invalid URI: The URI scheme is not valid.

### ISSUE THREAD

**Issue by swampthang** [unindented/electron-installer-windows#68] opened 2016-09-01 18:15 UTC
**What version of `electron-installer-windows` are you using?**
^0.2.0
**What version of `node` and `npm` are you using?**
2 info using npm@3.10.5
3 info using node@v4.4.7
**What operating system are you using?**
Mac OS Version 10.10.5
**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
Yes
**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
I have a root package.json file with scripts that contains:

```
"exe64": "electron-packager ./build 'GrooveAnimator' --platform=win32 --arch=x64 --out=dist/ --ignore=\"(dist|node_modules/electron.*)\" --icon=resources/groove-animator-win.png",
"set64": "electron-installer-windows --src dist/GrooveAnimator-win32-x64/ --dest dist/installers/x64/ --config config.json",
"packwin": "npm run exe64 && npm run set64"
```

Also have a config.json file with the following:

```
{
  "icon": "http://arcadebuilder.com/images/groove-animator-win.png",
  "iconUrl": "http://arcadebuilder.com/images/groove-animator-win.png",
  "tags": [
    "Utility",
    "SVG Animation"
  ],
  "options": {
    "iconUrl": "http://arcadebuilder.com/images/groove-animator-win.png"
  }
}
```

The app is set up like this...

```
app-
  build-
    contents (this is the dev testing environment and what the packaged apps are built from)
    package.json (contains only name, version, description, main, author and dependencies)
  dist- (destination folder for compile app)
  src-
    contents (this is the directory I work in and have listeners set up to copy to the build folder)
  package.json (contains the commands above)
  resource-
    app-icon.png
```

**What did you expect to happen?**
The application to be packaged

**What actually happened?**
I've attached the npm-debug.log file as well as a log file I copied my terminal output to. The error is:
`Invalid URI: The URI scheme is not valid.`

I tried several different ways of including the iconUrl. First, I tried just using the relative path like your example:
`resources/groove-animator-win.png`

I tried just using the relative path for `icon:` and placed the png on a server accessible from the Internet and using that URL for the iconUrl. I tried leaving out the icon in the exe64 process and tried both the remote icon url as well as the relative path. I continue to get this error no matter what I do. I didn't want to jump over the using electron-builder if the same issue is going to crop up. Really has me puzzled.

**Comment by swampthang** [comment] 2016-09-01 18:17
Here are the 2 files mentioned above...
[Archive.zip](https://github.com/unindented/electron-installer-windows/files/450419/Archive.zip)

**Comment by unindented** [comment] 2016-09-01 22:03
Try removing the `iconUrl` option first, see if things work. Once that's verified, add back `iconUrl`.

A couple of clarifications:
* `icon` has to be a relative path to a local `.ico` file (e.g. `./resources/groove_animator_icon.ico`).
* `iconUrl` has to be a URL to a remote `.ico` file (e.g. `http://arcadebuilder.com/images/groove_animator_icon.ico`.

**Comment by swampthang** [comment] 2016-09-02 12:08
Ahhh, thanks for the clarification. Sorry for not seeing this earlier.

**Comment by swampthang** [comment] 2016-09-02 12:39
Thanks for the quick response!

I removed the iconUrl reference and still getting the same error. I'd be happy to pay you to help me get this resolved - I'm up against a hard deadline. 

Attached: package.json, config.json, npm-debug.log and I created a log file from the terminal window output starting at the packwin command. 

Also, btw, the reason I was trying the png for the iconUrl is because [here](https://docs.nuget.org/create/nuspec-reference) it mentions this regarding iconUrl:

> A URL for the image to use as the icon for the package in the Manage NuGet Packages dialog box. This should be a 64x64-pixel .png file that has a transparent background.

That may not have anything to do with this situation but thought I'd add that to the discussion because it was linked from another discussion where this error was occurring.

Thanks again for the quick response.

[Archive.zip](https://github.com/unindented/electron-installer-windows/files/451997/Archive.zip)

**Comment by swampthang** [comment] 2016-09-02 12:46
Just uploaded the ico file to an http server and added back the iconUrl to the config like this:
```
{
  "icon": "resources/groove_animator_icon.ico",
  "tags": [
    "Utility",
    "SVG Animation"
  ],
  "options": {
    "iconUrl": "http://www.arcadebuilder.com/images/groove_animator_icon.ico"
  }
}
```

This is the terminal error I get after that:
```
grooveanimator (master) $ npm run packwin

> grooveanimator@ packwin /Users/swampthang/Documents/electron/grooveanimator
> npm run exe64 && npm run set64


> grooveanimator@ exe64 /Users/swampthang/Documents/electron/grooveanimator
> electron-packager ./build 'GrooveAnimator' --platform=win32 --arch=x64 --out=dist/ --ignore="(dist|node_modules/electron.*)" --icon=resources/groove_animator_icon.ico

Packaging app for platform win32 x64 using electron v1.2.8
Wrote new app to dist/GrooveAnimator-win32-x64

> grooveanimator@ set64 /Users/swampthang/Documents/electron/grooveanimator
> electron-installer-windows --src dist/GrooveAnimator-win32-x64/ --dest dist/installers/x64/ --config config.json

Creating package (this may take a while)
[Error: Error creating package: Error executing file (1):
mono /Users/swampthang/Documents/electron/grooveanimator/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /var/folders/h4/dlg727wx6js08_tth1qf_bzc0000gq/T/electron-11682-90436-zb6xwg/grooveanimator_1.0.0/nuget/grooveanimator.nuspec -BasePath /var/folders/h4/dlg727wx6js08_tth1qf_bzc0000gq/T/electron-11682-90436-zb6xwg/grooveanimator_1.0.0/grooveanimator -OutputDirectory /var/folders/h4/dlg727wx6js08_tth1qf_bzc0000gq/T/electron-11682-90436-zb6xwg/grooveanimator_1.0.0/nuget -NoDefaultExcludes
Invalid URI: The URI scheme is not valid.
] 'Error: Error creating package: Error executing file (1): \nmono /Users/swampthang/Documents/electron/grooveanimator/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /var/folders/h4/dlg727wx6js08_tth1qf_bzc0000gq/T/electron-11682-90436-zb6xwg/grooveanimator_1.0.0/nuget/grooveanimator.nuspec -BasePath /var/folders/h4/dlg727wx6js08_tth1qf_bzc0000gq/T/electron-11682-90436-zb6xwg/grooveanimator_1.0.0/grooveanimator -OutputDirectory /var/folders/h4/dlg727wx6js08_tth1qf_bzc0000gq/T/electron-11682-90436-zb6xwg/grooveanimator_1.0.0/nuget -NoDefaultExcludes\nInvalid URI: The URI scheme is not valid.\n\n    at /Users/swampthang/Documents/electron/grooveanimator/node_modules/electron-installer-windows/src/installer.js:273:21\n    at ChildProcess.<anonymous> (/Users/swampthang/Documents/electron/grooveanimator/node_modules/electron-installer-windows/src/installer.js:62:5)\n    at emitTwo (events.js:92:20)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:827:16)\n    at Socket.<anonymous> (internal/child_process.js:319:11)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at Pipe._onclose (net.js:486:12)'
```

**Comment by unindented** [comment] 2016-09-02 12:55
When's your deadline?

**Comment by swampthang** [comment] 2016-09-02 13:44
We release the app on the 7th so I need to be able to test on Windows as soon as possible.

**Comment by unindented** [comment] 2016-09-02 14:43
I'll try to take a look into it this weekend.

**Comment by swampthang** [comment] 2016-09-02 14:55
Thanks! Would it help if I gave you access to the repo? It's a private repo but I could invite you to it if you just wanted to glance at settings and where everything is located just in case structurally there's something amiss.

**Comment by unindented** [comment] 2016-09-02 14:55
@swampthang yup, that'd be helpful, just for this weekend.

**Comment by swampthang** [comment] 2016-09-02 15:14
ok, will email that to you. thanks

**Comment by swampthang** [comment] 2016-09-03 12:32
Also, here are my versions of mono and wine:
```
grooveanimator (master) $ mono --version
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 30 13:57:21 PDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
       	TLS:           normal
       	SIGSEGV:       altstack
       	Notification:  kqueue
       	Architecture:  amd64
       	Disabled:      none
       	Misc:          softdebug
       	LLVM:          supported, not enabled.
       	GC:            sgen
grooveanimator (master) $ wine --version
wine-1.8.2
```

**Comment by swampthang** [comment] 2016-09-04 18:19
Thank you so much for hanging in there and finding the issue. I'm now a serious fan of unindented!

**Comment by unindented** [comment] 2016-09-04 19:41
For reference, the error ended up being caused by the `homepage` being missing from the configuration, and Squirrel complaining about it with a cryptic `Invalid URI` error.

I'll try and add some validation of config options with explanatory messages when I have some more free time.

**Comment by nurseymybush** [comment] 2016-09-14 03:41
Sorry to come to this so late, but I'm having the same issue. What homepage attribute needs to be added to which configuration? package.json? Thanks for your help

**Comment by unindented** [comment] 2016-09-14 07:22
@nurseymybush Either you pass it as a parameter to `electron-installer-windows`, or you put it in your `package.json`, yes. Documentation here: https://github.com/unindented/electron-installer-windows#optionshomepage

**Comment by nurseymybush** [comment] 2016-09-14 23:06
Thank you! Another issue I had that is solved now is if the .exe created by electton-packager is not the same name as the one in package.json, electron-installer-windows will break. Electron-packager was creating app.exe and in package.json the name was "something-something-app".

**Comment by nidhir-systango** [comment] 2016-11-10 13:37
getting same error even after not giving any icon attribute.
just doing electron-installer-windows --src dist/app-win32-x64/ --dest dist/installers/


Invalid URI: The format of the URI could not be determined.
  Error: Error creating package: Error executing file (1): \nC:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\admin\\AppData\\Local\\Temp\\electron-11
 61010-8728-139g9g\\CoDesktopElectron_1.0.1\\nuget\\CoDesktopElectron.nuspec -BasePath C:\\Users\\admin\\AppData\\Local\\Temp\\electron-1161010-8728-139g9g\\CoDesktopElectron_1.0.1\\CoDesktopElectron -OutputDirectory C:\\Users\
\admin\\AppData\\Local\\Temp\\electron-1161010-8728-139g9g\\CoDesktopElectron_1.0.1\\nuget -NoDefaultExcludes\nInvalid URI:      The format of the URI could not be determined.\r\n\n    at    C:\\Users\\admin\\AppData\\Roaming\\npm\\no
 de_modules\\electron-installer-windows\\src\\installer.js:273:21\n      at ChildProcess.<anonymous> (C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (eve
nts.js:92:20)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:829:16)\n    at Socket.<anonymous> (internal/child_process.js:319:11)\n    at emitOne (events.js:77:13)\n    at Socket.emi
t (events.js:169:7)\n    at Pipe._onclose (net.js:486:12)'
PS C:\Users\admin\Downloads\New folder\new2\win_codesktop\app> [Error:   Error creating package: Error executing file (1):

please help me out of this.

**Comment by unindented** [comment] 2016-11-10 13:46
@nidhir-systango check that your package.json has a `homepage` attribute, or you pass that option to `electron-installer-windows`.

**Comment by nidhir-systango** [comment] 2016-11-10 14:07
{
  "name": "CoDesktopElectron",
  "version": "1.0.0",
  "author":"ankur",
  "private": true,
  "scripts": {
    "postinstall": "install-app-deps",
    "start": "npm install && npm run compile && electron ./app",
    "compile": "rimraf app/out && tsc",
    "pack": "npm run compile && build --dir",
    "dist": "npm run compile && build",
    "release": "npm run compile && build"
  },
  "build": {
    "appId": "org.develar.onshape",
    "category": "public.app-category.graphics-design",
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 150
        },
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "publish": null
    },
    "linux": {
      "publish": null,
      "target": ["deb", "AppImage"]
    }
  },
  "devDependencies": {
    "electron-builder": "^7.14.2",
    "electron": "1.4.3",
    "rimraf": "^2.5.4",
    "typescript": "^2.0.3",    
    "gulp": "^3.9.0",
    "fs-jetpack": "^0.7.0",
    "electron-prebuilt": "^0.31.0",
    "asar": "^0.7.2",
    "q": "^1.4.1",
    "gulp-copy": "0.0.2",
    "gulp-uglify": "^1.3.0",
    "gulp-usemin": "^0.3.12",
    "rcedit": "^0.3.0"
  }
}


No i don't  have

**Comment by nidhir-systango** [comment] 2016-11-10 14:12
Btw i can see homepage attribute in my node_modules/electron-installer-windows/package.json

{
  "name": "electron-installer-windows",
  "description": "Create a Windows package for your Electron app.",
  "version": "0.2.0",
  "license": "MIT",
  "author": {
    "name": "Daniel Perez Alvarez",
    "email": "unindented@gmail.com",
    "url": "http://unindented.org/"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/unindented/electron-installer-windows.git"
  },
  "keywords": [
    "electron",
    "windows"
  ],
  "main": "src/installer.js",
  "bin": {
    "electron-installer-windows": "src/cli.js"
  },
  "scripts": {
    "clean": "rimraf test/fixtures/out",
    "lint": "eslint .",
    "spec": "mocha",
    "test": "npm run clean && npm run lint && npm run spec"
  },
  "dependencies": {
    "asar": "^0.9.0",
    "async": "^1.5.1",
    "debug": "^2.2.0",
    "fs-extra": "^0.26.0",
    "glob": "^6.0.3",
    "lodash": "^4.0.1",
    "temp": "^0.8.3",
    "yargs": "^3.32.0"
  },
  "devDependencies": {
    "chai": "^3.4.1",
    "eslint": "^1.10.3",
    "eslint-config-standard": "^4.4.0",
    "eslint-plugin-standard": "^1.3.1",
    "finalhandler": "^0.4.1",
    "mocha": "^2.4.2",
    "retry": "^0.9.0",
    "rimraf": "^2.5.1",
    "serve-static": "^1.10.2"
  },
  "gitHead": "e8a252be1c4ffcb20523897d54f8340c29698bc1",
  "bugs": {
    "url": "https://github.com/unindented/electron-installer-windows/issues"
  },
  "homepage": "https://github.com/unindented/electron-installer-windows#readme",
  "_id": "electron-installer-windows@0.2.0",
  "_shasum": "cbcf2dc8450c9e6c8abca56f5c87115699e72052",
  "_from": "electron-installer-windows@latest",
  "_npmVersion": "2.14.12",
  "_nodeVersion": "4.2.6",
  "_npmUser": {
    "name": "unindented",
    "email": "unindented@gmail.com"
  },
  "dist": {
    "shasum": "cbcf2dc8450c9e6c8abca56f5c87115699e72052",
    "tarball": "https://registry.npmjs.org/electron-installer-windows/-/electron-installer-windows-0.2.0.tgz"
  },
  "maintainers": [
    {
      "name": "unindented",
      "email": "unindented@gmail.com"
    }
  ],
  "_npmOperationalInternal": {
    "host": "packages-5-east.internal.npmjs.com",
    "tmp": "tmp/electron-installer-windows-0.2.0.tgz_1454949420078_0.764820613199845"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/electron-installer-windows/-/electron-installer-windows-0.2.0.tgz"
}

**Comment by unindented** [comment] 2016-11-10 14:39
Dude, the second one you posted is the `package.json` for this library, not your app. You need to have `homepage` in **your** app's `package.json`.

**Comment by nidhir-systango** [comment] 2016-11-10 14:40
oh, sorry for that i don't have homepage in my app can you give me suggestions of what it should be

**Comment by unindented** [comment] 2016-11-10 15:46
Just put any URL, like your GitHub repo or something.

**Comment by nidhir-systango** [comment] 2016-11-10 16:07
got new error:


PS C:\Users\admin\Downloads\New folder\new2\win_codesktop> electron-installer-windows --src dist/app-win32-x64/ --dest dist/installers/


Creating package (this may take a while)
[Error: Error creating package: Error executing file (1):
C:\Users\admin\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\admin\AppData\Local\Temp\electron-1161010-2392-1xz532o\CoDesktopElectron_1.0.0\nuget\CoDesktopElectron.nuspec -Bas
ePath C:\Users\admin\AppData\Local\Temp\electron-1161010-2392-1xz532o\CoDesktopElectron_1.0.0\CoDesktopElectron -OutputDirectory C:\Users\admin\AppData\Local\Temp\electron-1161010-2392-1xz532o\CoDesktopElectron_1.0.0\nuget -No
DefaultExcludes
The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has incomplete content. List of possible elements expected: 'description' in namespace 'http://schemas.microsoft.com/packaging/201
0/07/nuspec.xsd'.
] 'Error: Error creating package: Error executing file (1): \nC:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\admin\\AppData\\Local\\Temp\\electron-11
61010-2392-1xz532o\\CoDesktopElectron_1.0.0\\nuget\\CoDesktopElectron.nuspec -BasePath C:\\Users\\admin\\AppData\\Local\\Temp\\electron-1161010-2392-1xz532o\\CoDesktopElectron_1.0.0\\CoDesktopElectron -OutputDirectory C:\\User
s\\admin\\AppData\\Local\\Temp\\electron-1161010-2392-1xz532o\\CoDesktopElectron_1.0.0\\nuget -NoDefaultExcludes\nThe element \'metadata\' in namespace \'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd\' has incomple
te content. List of possible elements expected: \'description\' in namespace \'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd\'.\r\n\n    at C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\electron-installer-
windows\\src\\installer.js:273:21\n    at ChildProcess.<anonymous> (C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (events.js:92:20)\n    at ChildProc
ess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:829:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)'

**Comment by unindented** [comment] 2016-11-10 16:11
If you read the error, it says: "List of possible elements expected: 'description' in namespace"

Try adding a description to your `package.json` file.

Also, this library provides an example app: https://github.com/unindented/electron-installer-windows/tree/master/example

It may be useful for you to compile the app, see how it is working, and compare it to yours.

**Comment by nidhir-systango** [comment] 2016-11-10 16:15
Added description but still same error...

**Comment by unindented** [comment] 2016-11-10 16:16
Compare your application to the example. It looks like your problem is related to your specific setup, not the library itself. I'll close the issue so that this doesn't go on forever.

**Closed by unindented** 2016-11-10 16:16 UTC
