### ISSUE TITLE
Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by privatemiao** [unindented/electron-installer-windows#151] opened 2017-02-08 02:46 UTC
C:\Users\mel\tmp\app>electron-installer-windows --src dist/app-win32-x64 --dest dist/installers
Creating package (this may take a while)
Error: Error creating package: Error executing file (1):
C:\Users\mel\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\mel\AppData\Local\Temp\electron-11718-12188-ueez21.f3oqq1714i\app_0.0.0\nuget\app.nuspec -BasePath C:\Users\mel\AppData\Local\Temp\electron-11718-12188-ueez21.f3oqq1714i\app_0.0.0\app -OutputDirectory C:\Users\mel\AppData\Local\Temp\electron-11718-12188-ueez21.f3oqq1714i\app_0.0.0\nuget -NoDefaultExcludes
Invalid URI: The format of the URI could not be determined.

    at C:\Users\mel\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:273:21
    at ChildProcess.<anonymous> (C:\Users\mel\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:62:5)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12) 'Error: Error creating package: Error executing file (1): \nC:\\Users\\mel\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\mel\\AppData\\Local\\Temp\\electron-11718-12188-ueez21.f3oqq1714i\\app_0.0.0\\nuget\\app.nuspec -BasePath C:\\Users\\mel\\AppData\\Local\\Temp\\electron-11718-12188-ueez21.f3oqq1714i\\app_0.0.0\\app -OutputDirectory C:\\Users\\mel\\AppData\\Local\\Temp\\electron-11718-12188-ueez21.f3oqq1714i\\app_0.0.0\\nuget -NoDefaultExcludes\nInvalid URI: The format of the URI could not be determined.\r\n\n    at C:\\Users\\mel\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:273:21\n    at ChildProcess.<anonymous> (C:\\Users\\mel\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (events.js:111:20)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:885:16)\n    at Socket.<anonymous> (internal/child_process.js:334:11)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at Pipe._handle.close [as _onclose] (net.js:501:12)'

**Comment by daaru00** [comment] 2017-02-12 13:17
Check if you are using a path (like` iconUrl: './icons/icon.ico'`) in iconUrl option. If you did
 change it to `iconUrl: 'file:///C:/Users/......./icons/icon.ico'` or simply use icon option

**Comment by karlbateman** [comment] 2017-02-26 18:51
Same issue here, running the following command `electron-installer-windows --src dist/app-win32-x64 --dest dist/installers`.

**Comment by unindented** [comment] 2017-02-26 18:52
Duplicate of https://github.com/unindented/electron-installer-windows/issues/55

**Closed by unindented** 2017-02-26 18:52 UTC

**Comment by RangerMauve** [comment] 2017-10-03 18:44
Sorry to revive this, but @daaru00 mentioned to use the "icon option" for a local path, but I'm not seeing that documented anywhere
